

CREATE DATABASE BD_AIRPORT DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'nico'@'localhost' IDENTIFIED BY '1234';
GRANT ALL ON BD_AIRPORT.* TO 'nico'@'localhost' IDENTIFIED BY '1234';

CREATE USER 'flo'@'localhost' IDENTIFIED BY '1234';
GRANT ALL ON BD_AIRPORT.* TO 'flo'@'localhost' IDENTIFIED BY '1234';