DROP USER java CASCADE;
CREATE USER java IDENTIFIED BY JAVA ACCOUNT UNLOCK;
GRANT CREATE SESSION TO java;
GRANT ALTER SESSION TO java;
ALTER USER java QUOTA UNLIMITED ON users;
GRANT CREATE TABLE TO java;
GRANT CREATE DATABASE LINK TO java;
