/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application_Bagages;

import Tools.Bd;
import Tools.BdType;
import Tools.PropertiesReader;

import javax.swing.*;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.sql.SQLException;

/**
 *
 * @author Nicolas
 */
public class Application_Bagage extends javax.swing.JFrame {
    Bd MySql;
    Login Log;
    liste_Bagages ListeBag;
    Socket Serveur;
    /**
     * Creates new form Login
     */
    public Application_Bagage()
    {
        initComponents();
    }

    public Application_Bagage(boolean ouverture) {
        initComponents();
        this.setVisible(ouverture);
        this.setEnabled(false);
        Socket c = null;
        try {
            //TODO Lecture via fichier properties
            c = new Socket(InetAddress.getByName(PropertiesReader.getProperties("ServerName")),Integer.valueOf(PropertiesReader.getProperties("Port")));
        }
        catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getLocalizedMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
        this.setEnabled(true);

        Log = new Login(this,true,c);
        Log.setVisible(true);

        try {
            MySql = new Bd(BdType.MySql);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getLocalizedMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getLocalizedMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bagagisteLabel = new javax.swing.JLabel();
        bagagisteLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultatJTable = new javax.swing.JTable();
        volsLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application Bagages");

        bagagisteLabel.setText("Bagagiste :");

        bagagisteLabel2.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        bagagisteLabel2.setText("non prenom");

        resultatJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultatJTable.setCellSelectionEnabled(true);
        resultatJTable.setColumnSelectionAllowed(true);
        resultatJTable.setEnabled(false);
        resultatJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultatJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultatJTable);

        volsLabel.setText("Vols prévus ce jour :");

        optionMenu.setText("Options");

        jMenuItem1.setText("Disconnect");
        optionMenu.add(jMenuItem1);

        jMenuBar1.add(optionMenu);

        aboutMenu.setText("About?");
        jMenuBar1.add(aboutMenu);

        helpMenu.setText("Help");
        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bagagisteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(bagagisteLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(volsLabel))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagagisteLabel)
                    .addComponent(bagagisteLabel2))
                .addGap(24, 24, 24)
                .addComponent(volsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultatJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultatJTableMouseClicked
        int row = resultatJTable.rowAtPoint(evt.getPoint());
        int col = resultatJTable.columnAtPoint(evt.getPoint());
        
        if (row >= 0 && col >= 0) {
            System.out.println("coucou");
            ListeBag = new liste_Bagages((String)resultatJTable.getValueAt(col, row));
            ListeBag.setVisible(true);
        }
    }//GEN-LAST:event_resultatJTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application_Bagage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Application_Bagage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JLabel bagagisteLabel;
    private javax.swing.JLabel bagagisteLabel2;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JTable resultatJTable;
    private javax.swing.JLabel volsLabel;
    // End of variables declaration//GEN-END:variables
}
