/*
 * Copyright 2017 floryan.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Application_Bagages;

import LUGAP.NetworkObject.Bagage;

public class DetailsBagage extends javax.swing.JDialog {

    /**
     * Creates new form DetailsBagage
     */
    public DetailsBagage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DetailsBagage(java.awt.Frame parent, boolean modal, Bagage b) {
        super(parent, modal);
        initComponents();
        NumBilletTF.setText(b.getNumeroBillet());
        NumBagageTF.setText(b.getNumeroBagage());
        ValiseRB.setSelected(b.isValise());
        ReceptionnerCB.setSelected(b.isReception());
        VerifierCB.setSelected(b.isVerifier());
        RemarqueTA.setText(b.getRemarque());
        PoidsTF.setText(String.valueOf(b.getPoids()));
        if (b.getCharger() == 'R') {
            RefuserCB.setSelected(true);
        } else if (b.getCharger() == 'O') {
            ChargeCB.setSelected(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsBagage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsBagage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsBagage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsBagage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DetailsBagage dialog = new DetailsBagage(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public Bagage getBagage() {
        return new Bagage(NumBagageTF.getText(), Double.parseDouble(PoidsTF.getText()), ValiseRB.isSelected(), NumBilletTF.getText(), ReceptionnerCB.isSelected(), ChargeCB.isSelected() ? 'O' : RefuserCB.isSelected() ? 'R' : 'N', VerifierCB.isSelected(), RemarqueTA.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChargementBG = new javax.swing.ButtonGroup();
        NumeroBagageLabel = new javax.swing.JLabel();
        NumBagageTF = new javax.swing.JTextField();
        PoidsLabel = new javax.swing.JLabel();
        PoidsTF = new javax.swing.JTextField();
        NumeroBilletLabel = new javax.swing.JLabel();
        NumBilletTF = new javax.swing.JTextField();
        ValiseRB = new javax.swing.JRadioButton();
        ReceptionnerCB = new javax.swing.JCheckBox();
        ChargeCB = new javax.swing.JCheckBox();
        VerifierCB = new javax.swing.JCheckBox();
        RefuserCB = new javax.swing.JCheckBox();
        RemarquesLabel = new javax.swing.JLabel();
        RemarqueSPTA = new javax.swing.JScrollPane();
        RemarqueTA = new javax.swing.JTextArea();

        setTitle("Détails sur les bagages");
        setType(java.awt.Window.Type.UTILITY);

        NumeroBagageLabel.setText("Numéro du bagage:");

        NumBagageTF.setFocusable(false);

        PoidsLabel.setText("Poids: ");

        PoidsTF.setFocusable(false);

        NumeroBilletLabel.setText("Numéro de billet: ");

        NumBilletTF.setFocusable(false);

        ValiseRB.setText("Valise ? ");
        ValiseRB.setEnabled(false);
        ValiseRB.setFocusable(false);

        ReceptionnerCB.setText("Réceptionné ? ");
        ReceptionnerCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptionnerCBActionPerformed(evt);
            }
        });

        ChargementBG.add(ChargeCB);
        ChargeCB.setText("Chargé ?");
        ChargeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeCBActionPerformed(evt);
            }
        });

        VerifierCB.setText("Vérifié par la douane ?");
        VerifierCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifierCBActionPerformed(evt);
            }
        });

        ChargementBG.add(RefuserCB);
        RefuserCB.setText("Refusé ? ");
        RefuserCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefuserCBActionPerformed(evt);
            }
        });

        RemarquesLabel.setText("Remarques: ");

        RemarqueTA.setColumns(20);
        RemarqueTA.setRows(5);
        RemarqueSPTA.setViewportView(RemarqueTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroBagageLabel)
                            .addComponent(PoidsLabel))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumBagageTF)
                            .addComponent(PoidsTF)))
                    .addComponent(RemarqueSPTA)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumeroBilletLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(NumBilletTF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValiseRB)
                            .addComponent(RemarquesLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReceptionnerCB)
                                    .addComponent(ChargeCB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RefuserCB)
                                    .addComponent(VerifierCB))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroBagageLabel)
                    .addComponent(NumBagageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoidsLabel)
                    .addComponent(PoidsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValiseRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroBilletLabel)
                    .addComponent(NumBilletTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceptionnerCB)
                    .addComponent(VerifierCB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChargeCB)
                    .addComponent(RefuserCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemarquesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemarqueSPTA, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChargeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeCBActionPerformed
        System.out.println("Charge: " + ChargeCB.isSelected());
        if (ChargeCB.isSelected()) {
            if (!ReceptionnerCB.isSelected()) {
                ReceptionnerCB.setSelected(true);
            }
        }
    }//GEN-LAST:event_ChargeCBActionPerformed

    private void RefuserCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefuserCBActionPerformed
        System.out.println("Refuser: " + RefuserCB.isSelected());
        if (RefuserCB.isSelected()) {
            if (!ReceptionnerCB.isSelected()) {
                ReceptionnerCB.setSelected(true);
            }
            if (!VerifierCB.isSelected()) {
                VerifierCB.setSelected(true);
            }
        }
    }//GEN-LAST:event_RefuserCBActionPerformed

    private void VerifierCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifierCBActionPerformed
        System.out.println("Verifier: " + VerifierCB.isSelected());
        VerifierCB.setSelected(!VerifierCB.isSelected());
        System.out.println("Verifier: " + VerifierCB.isSelected());
        if (VerifierCB.isSelected()) {
            if (!ReceptionnerCB.isSelected()) {
                ReceptionnerCB.setSelected(true);
            }
        }
    }//GEN-LAST:event_VerifierCBActionPerformed

    private void ReceptionnerCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptionnerCBActionPerformed
        System.out.println("Receptionner: " + ReceptionnerCB.isSelected());

    }//GEN-LAST:event_ReceptionnerCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChargeCB;
    private javax.swing.ButtonGroup ChargementBG;
    private javax.swing.JTextField NumBagageTF;
    private javax.swing.JTextField NumBilletTF;
    private javax.swing.JLabel NumeroBagageLabel;
    private javax.swing.JLabel NumeroBilletLabel;
    private javax.swing.JLabel PoidsLabel;
    private javax.swing.JTextField PoidsTF;
    private javax.swing.JCheckBox ReceptionnerCB;
    private javax.swing.JCheckBox RefuserCB;
    private javax.swing.JScrollPane RemarqueSPTA;
    private javax.swing.JTextArea RemarqueTA;
    private javax.swing.JLabel RemarquesLabel;
    private javax.swing.JRadioButton ValiseRB;
    private javax.swing.JCheckBox VerifierCB;
    // End of variables declaration//GEN-END:variables
}
