/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application_Bagages;

import LUGAP.NetworkObject.Bagage;
import LUGAP.NetworkObject.Table;

import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author Nicolas
 */
public class Liste_Bagages extends javax.swing.JFrame {

    private Table BagagesTable;

    /**
     * Creates new form liste_Bagages
     */
    public Liste_Bagages() {
        initComponents();
    }

    public Liste_Bagages(String vol, Table t) {
        initComponents();
        setTitle("Vol: " + vol);
        VolLabel2.setText(vol);
        BagagesTable = t;
        UpdateJTable();
    }

    private void UpdateJTable() {
        ResultatJTable.setModel(new DefaultTableModel(BagagesTable.getChamps(), BagagesTable.getTete()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightPM = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        VolLabel = new javax.swing.JLabel();
        BagagesLabel = new javax.swing.JLabel();
        VolLabel2 = new javax.swing.JLabel();
        ScrollPane1 = new javax.swing.JScrollPane();
        ResultatJTable = new javax.swing.JTable();

        RightPM.setInvoker(ResultatJTable);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Couocu");
        RightPM.add(jCheckBoxMenuItem1);

        jMenuItem1.setText("jMenuItem1");
        RightPM.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VolLabel.setText("Vol :");

        BagagesLabel.setText("Bagages pour ce vol :");

        VolLabel2.setText("Nom du vol");

        ResultatJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Identifiant", "Poids", "Type", "Réceptioné(O/N)", "Chargé en soute (O/N)", "Vérifié par la douane (O/N)", "Remarques"
            }
        ));
        ResultatJTable.setCellSelectionEnabled(true);
        ResultatJTable.setEnabled(false);
        ResultatJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultatJTableMouseClicked(evt);
            }
        });
        ScrollPane1.setViewportView(ResultatJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VolLabel)
                                .addGap(18, 18, 18)
                                .addComponent(VolLabel2))
                            .addComponent(BagagesLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolLabel)
                    .addComponent(VolLabel2))
                .addGap(25, 25, 25)
                .addComponent(BagagesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResultatJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultatJTableMouseClicked
        if (evt.getClickCount() == 1) {
            int pos = ResultatJTable.rowAtPoint(evt.getPoint());
            Vector<String> v = BagagesTable.getChamps().remove(pos);
            DetailsBagage db = new DetailsBagage(this, true, Bagage.FromVector(v));
            db.setVisible(true);
            BagagesTable.getChamps().add(pos, db.getBagage().toVector());
            UpdateJTable();
        }
    }//GEN-LAST:event_ResultatJTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_Bagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_Bagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_Bagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_Bagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Liste_Bagages().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BagagesLabel;
    private javax.swing.JTable ResultatJTable;
    private javax.swing.JPopupMenu RightPM;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JLabel VolLabel;
    private javax.swing.JLabel VolLabel2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
