CREATE DATABASE BD_AIRPORT DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
-- SHOW TABLES;
-- DESCRIBE table; 

CREATE USER 'nico' IDENTIFIED BY '1234';
GRANT ALL ON BD_AIRPORT.* TO 'nico' IDENTIFIED BY '1234';

CREATE USER 'java'
  IDENTIFIED BY 'java';
GRANT SELECT ON BD_AIRPORT.* TO 'java';

CREATE USER 'flo' IDENTIFIED BY '1234';
GRANT ALL ON BD_AIRPORT.* TO 'flo' IDENTIFIED BY '1234';