DROP DATABASE bd_airport;
CREATE DATABASE bd_airport
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
-- SHOW TABLES;
-- DESCRIBE table;
DROP USER 'nico';
CREATE USER 'nico'
  IDENTIFIED BY '1234';
GRANT ALL ON bd_airport.* TO 'nico'
IDENTIFIED BY '1234';

SHOW GRANTS FOR 'java';

DROP USER 'java';
CREATE USER 'java'
  IDENTIFIED BY 'java';
GRANT SELECT,UPDATE,INSERT ON bd_airport.* TO 'java';

DROP USER 'flo';
CREATE USER 'flo'
  IDENTIFIED BY '1234';
GRANT ALL ON bd_airport.* TO 'flo'
IDENTIFIED BY '1234';